import Head from 'next/head'
import { Inter } from '@next/font/google'
import Footer from '../Components/Footer/Footer'
import Contact from '../Components/Contact/Contact'
import Banner from '../Components/Banner/Banner'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Shakhawat Hossain</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://icons-for-free.com/iconfiles/png/512/binder+circle+folder+portfolio+record+icon-1320196711026051008.png" />
      </Head>
        <Banner></Banner>
        <Contact></Contact>
        <Footer></Footer>
    </>
  )
}
